export const learningConfig = {
    courses:{
        isHidden: false,
        mainTitle: 'Available Courses',
        mainTitleHighlightedWord: 'Courses',
        data : [
        {
                imageUrl: "/bookifai.jpeg",
                title: "OpenAi API Integration in Python",
                description: "Create your own AI-powered custom bot powered with openai api, and use streamlit for creating a user interface for your bot",
                price: "$10",
                actionLink: "mailto:rabeekiblawi@gmail.com",
                actionText: "Register",
                isHidden: false,
                visibleHome: true,
                duration: "20 Hours",
                startDate: "2024-01-01",
                endDate: "2024-04-01",
                target: "Book lovers, Discord users",
                outcomes: "AI-powered bot, Streamlit UI",
                courseLink: "https://www.bookifai.com"
            },
            {
                imageUrl: "/MirageXR.jpg",
                title: "MirageXR",
                description: `Prototype Arduino or ESP projects faster with MirageXR. Our platform connects virtual electronics to your physical hardware, enabling quick testing and development. Using our AR/XR app and Arduino/ESP library, control virtual components with your real board—no extra parts needed.Bridge the physical and virtual worlds in your projects!`,
                price: "$10",
                actionLink: "https://www.miragexr.com",
                actionText: "Join Waitlist",
                isHidden: true,
                visibleHome: false,
                duration: "Ongoing",
                startDate: "2023-05-01",
                endDate: "",
                target: "Developers, Makers",
                outcomes: "Faster prototyping, integration of AR/XR with hardware",
                courseLink: "https://www.bookifai.com"
            },
            {
                imageUrl: "/unity_chatgpt.png",
                title: "OpenAI Wrapper for Unity",
                description: "Our Unity package allows you to easily integrate OpenAI's Models into your Unity projects. We provided a simple API that allows you to interact and chain multiple models together to create complex AI behaviors in your game or simulation. Our package is designed to be easy to use and flexible to fit your needs. We also provide a set of example scenes to get you started quickly!",
                price: "$10",
                actionLink: "https://github.com/rabeeqiblawi/Choroid-Input-System",
                actionText: "View On Github",
                isHidden: true,
                visibleHome: true,
                duration: "Ongoing",
                startDate: "2023-06-01",
                endDate: "",
                target: "Game Developers, AI Enthusiasts",
                outcomes: "Enhanced AI capabilities in Unity, simplified AI integration",
                courseLink: "https://www.bookifai.com"
            },
            {
                imageUrl: "/cfwm2.jpg",
                title: "Come Fly With Me (Prototype)",
                description: `Ever wanted to fly like a bird? Come Fly With Me is a VR experience that allows you to do just that! You can fly and explore the world from a bird's eye view!`,
                price: "$10",
                actionLink: "https://www.youtube.com/watch?v=oted6xBF0z8",
                actionText: "More",
                isHidden: true,
                visibleHome: false,
                duration: "1-2 hours",
                startDate: "2023-07-01",
                endDate: "2023-07-01",
                target: "VR Enthusiasts, Adventure Seekers",
                outcomes: "Immersive VR experience, exploration of virtual environments",
                courseLink: "https://www.bookifai.com"
            },
            {
                imageUrl: "/notFound.png",
                title: "test (not at Home page)",
                description: "TEST",
                price: "$10",
                actionLink: "",
                actionText: "View Project",
                isHidden: true,
                visibleHome: false,
                duration: "",
                startDate: "",
                endDate: "",
                target: "Testers",
                outcomes: "Testing purposes",
                courseLink: "https://www.bookifai.com"
            },
        ] 
    },
}